/*Creation of the main table*/
DROP TABLE periodicElement;
CREATE TABLE periodicElement (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'All caracteristics set in the table correspond to those at the temperature of 20 degre Celsius',
	nameElement VARCHAR(15) NOT NULL UNIQUE COMMENT 'name of the element', 
	shortName VARCHAR(3) NOT NULL UNIQUE COMMENT 'shortname of the element',
	state VARCHAR(10) NOT NULL,
	type VARCHAR(25)
);
/*Full the table periodicElement*/
INSERT INTO periodicElement (nameElement,shortName,state,type) 
VALUES 	('Hydrogene','H','Gas','Nonmetal'),
	('Helium','He','Gas','Noble gas'),
	('Lithium','Li','Solid','Alcalin metal'),
	('Beryllium','Be','Solid','Alcalin earth metal'),
	('Bore', 'B', 'Solid', 'Metalloid'),
	('Carbone', 'C', 'Solid', 'Nonmetal'),
	('Azote', 'N', 'Gas', 'Nonmetal'),
	('Oxygene', 'O', 'Gas', 'Nonmetal'),
	('Fluor', 'F', 'Gas', 'Nonmetal'),
	('Neon', 'Ne', 'Gas', 'Noble gas'),
	('Sodium', 'Na', 'Solid', 'Alcalin metal'),
	('Magnesium', 'Mg', 'Solid', 'Alcalin earth metal'),
	('Aluminium', 'Al', 'Solid', 'Poor metal'),
	('Silicium', 'Si', 'Solid', 'Metalloid'),
	('Phosphore', 'P', 'Solid', 'Nonmetal'),
	('Soufre', 'S', 'Solid', 'Nonmetal'),
	('Chlore', 'Cl', 'Gas', 'Nonmetal'),
	('Argon', 'Ar', 'Gas', 'Noble gas'),
	('Potassium', 'K', 'Solid', 'Alcalin metal'),
	('Calcium', 'Ca', 'Solid', 'Alcalin earth metal'),
	('Scandium', 'Sc', 'Solid', 'Transition metal'),
	('Titane', 'Ti', 'Solid', 'Transition metal'),
	('Vanadium', 'V', 'Solid', 'Transition metal'),
	('Chrome', 'Cr', 'Solid', 'Transition metal'),
	('Manganese', 'Mn', 'Solid', 'Transition metal'),
	('Iron', 'Fe', 'Solid', 'Transition metal'),
	('Cobalt', 'Co', 'Solid', 'Transition metal'),
	('Nickel', 'Ni', 'Solid', 'Transition metal'),
	('Copper', 'Cu', 'Solid', 'Transition metal'),
	('Zinc', 'Zn', 'Solid', 'Transition metal'),
	('Gallium', 'Ga', 'Solid', 'Poor metal'),
	('Germanium', 'Ge', 'Solid', 'Metalloid'),
	('Arsenic', 'As', 'Solid', 'Metalloid'),
	('Selenium', 'Se', 'Solid', 'Nonmetal'),
	('Brome', 'Br', 'Liquid', 'Nonmetal'),
	('Krypton', 'Kr', 'Gas', 'Noble gas'),
	('Rubidium', 'Rb', 'Solid', 'Alcalin metal'),
	('Strontium', 'Sr', 'Solid', 'Alcalin earth metal'),
	('Yttrium', 'Y', 'Solid', 'Transition metal'),
	('Zirconium', 'Zr', 'Solid', 'Transition metal'),
	('Niobium', 'Nb', 'Solid', 'Transition metal'),
	('Molybdene', 'Mo', 'Solid', 'Transition metal'),
	('Technetium', 'Tc', 'Solid', 'Transition metal'),
	('Ruthenium', 'Ru', 'Solid', 'Transition metal'),
	('Rhodium', 'Rh', 'Solid', 'Transition metal'),
	('Palladium', 'Pd', 'Solid', 'Transition metal'),
	('Silver', 'Ag', 'Solid', 'Transition metal'),
	('Cadmium', 'Cd', 'Solid', 'Transition metal'),
	('Indium', 'In', 'Solid', 'Poor metal'),
	('Tin', 'Sn', 'Solid', 'Poor metal'),
	('Antimoine', 'Sb', 'Solid', 'Metalloid'),
	('Tellure', 'Te', 'Solid', 'Metalloid'),
	('Iode', 'I', 'Solid', 'Nonmetal'),
	('Xenon', 'Xe', 'Gas', 'Noble gas'),
	('Cesium', 'Cs', 'Solid', 'Alcalin metal'),
	('Baryum', 'Ba', 'Solid', 'Alcalin earth metal'),
	('Lanthane', 'La', 'Solid', 'Lanthanide'),
	('Cerium', 'Ce', 'Solid', 'Lanthanide'),
	('Praseodyme', 'Pr', 'Solid', 'Lanthanide'),
	('Neodyme', 'Nd', 'Solid', 'Lanthanide'),
	('Promethium', 'Pm', 'Solid', 'Lanthanide'),
	('Samarium', 'Sm', 'Solid', 'Lanthanide'),
	('Europium', 'Eu', 'Solid', 'Lanthanide'),
	('Gadolinium', 'Gd', 'Solid', 'Lanthanide'),
	('Terbium', 'Tb', 'Solid', 'Lanthanide'),
	('Dysprosium', 'Dy', 'Solid', 'Lanthanide'),
	('Holmium', 'Ho', 'Solid', 'Lanthanide'),
	('Erbium', 'Er', 'Solid', 'Lanthanide'),
	('Thulium', 'Tm', 'Solid', 'Lanthanide'),
	('Ytterbium', 'Yb', 'Solid', 'Lanthanide'),
	('Lutecium', 'Lu', 'Solid', 'Lanthanide'),
	('Hafnium', 'Hf', 'Solid', 'Transition metal'),
	('Tantale', 'Ta', 'Solid', 'Transition metal'),
	('Tungstene', 'W', 'Solid', 'Transition metal'),
	('Rhenium', 'Re', 'Solid', 'Transition metal'),
	('Osmium', 'Os', 'Solid', 'Transition metal'),
	('Iridium', 'Ir', 'Solid', 'Transition metal'),
	('Platinium', 'Pt', 'Solid', 'Transition metal'),
	('Gold', 'Au', 'Solid', 'Transition metal'),
	('Mercure', 'Hg', 'Liquid', 'Transition metal'),
	('Thallium', 'Tl', 'Solid', 'Poor metal'),
	('Lead', 'Pb', 'Solid', 'Poor metal'),
	('Bismuth', 'Bi', 'Solid', 'Poor metal'),
	('Polonium', 'Po', 'Solid', 'Poor metal'),
	('Astate', 'At', 'Solid', 'Metalloid'),
	('Radon', 'Rn', 'Gas', 'Noble gas'),
	('Francium', 'Fr', 'Solid', 'Alcalin metal'),
	('Radium', 'Ra', 'Solid', 'Alcalin earth metal'),
	('Actinium', 'Ac', 'Solid', 'Actinide'),
	('Thorium', 'Th', 'Solid', 'Actinide'),
	('Protactinium', 'Pa', 'Solid', 'Actinide'),
	('Uranium', 'U', 'Solid', 'Actinide'),
	('Neptunium', 'Np', 'Solid', 'Actinide'),
	('Plutonium', 'Pu', 'Solid', 'Actinide'),
	('Americium', 'Am', 'Solid', 'Actinide'),
	('Curium', 'Cm', 'Solid', 'Actinide'),
	('Berkelium', 'Bk', 'Solid', 'Actinide'),
	('Californium', 'Cf', 'Solid', 'Actinide'),
	('Einsteinium', 'Es', 'Solid', 'Actinide'),
	('Fermium', 'Fm', 'Solid', 'Actinide'),
	('Mendelevium', 'Md', 'Solid', 'Actinide'),
	('Nobelium', 'No', 'Solid', 'Actinide'),
	('Lawrencium', 'Lr', 'Solid', 'Actinide'),
	('Rutherfordium', 'Rf', 'Unknown', 'Transition metal'),
	('Dubnium', 'Db', 'Unknown', 'Transition metal'),
	('Seaborgium', 'Sg', 'Unknown', 'Transition metal'),
	('Borhrium', 'Bh', 'Unknown', 'Transition metal'),
	('Hassium', 'Hs', 'Unknown', 'Transition metal');
INSERT INTO periodicElement (nameElement,shortName,state) 
VALUES 	('Meitnerium', 'Mt', 'Unknown'),
	('Darmstadtium', 'Ds', 'Unknown'),
	('Roentgenium', 'Rg', 'Unknown'),
	('Copernicium', 'Cn', 'Unknown'),
	('Nihonium', 'Nh', 'Unknown'),
	('Flerovium', 'Fl', 'Unknown'),
	('Moscuvium', 'Mc', 'Unknown'),
	('Livermorium', 'Lv', 'Unknown'),
	('Tennesse', 'Ts', 'Unknown'),
	('Oganesson', 'Og', 'Unknown');
